import { STAGE_BY_ID } from "@/lib/stages";
import type { StageState } from "@/lib/use-cascade";

/**
 * Combines the four stage outputs into a single sourced Markdown document,
 * with a header noting the concept and that every stage was grounded in the
 * one before it.
 */
export function buildExportDoc(args: {
  concept: string;
  hadReferenceDoc: boolean;
  stages: StageState[];
}): string {
  const { concept, hadReferenceDoc, stages } = args;
  const date = new Date().toISOString().slice(0, 10);

  const lines: string[] = [];
  lines.push(`# Cascade Launch Stack`);
  lines.push("");
  lines.push(`> Generated by Cascade on ${date}.`);
  lines.push(
    `> Each section is grounded in the section before it${
      hadReferenceDoc ? ", and in the reference document you provided" : ""
    } — one idea, four aligned deliverables.`,
  );
  lines.push("");
  lines.push(`## Product Concept`);
  lines.push("");
  lines.push(concept.trim());
  lines.push("");
  lines.push(`---`);
  lines.push("");

  for (const stage of stages) {
    const meta = STAGE_BY_ID[stage.id];
    if (!stage.output.trim()) continue;
    lines.push(`# ${meta.glyph} ${meta.title}`);
    lines.push("");
    lines.push(stage.output.trim());
    lines.push("");
    lines.push(`---`);
    lines.push("");
  }

  return lines.join("\n");
}

/** Triggers a client-side download of the given Markdown text. */
export function downloadMarkdown(filename: string, markdown: string) {
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
