import { anthropic } from "@ai-sdk/anthropic";
import { streamText } from "ai";
import { NextRequest } from "next/server";
import {
  buildStageContext,
  STAGE_BY_ID,
  type PriorStage,
  type StageId,
  type StageRevisionInput,
} from "@/lib/stages";

// Each stage is generated by its own request so the client can stream them as a
// visible waterfall and feed each completed output into the next.
//
// Model calls go directly to the Anthropic API (the provider reads
// ANTHROPIC_API_KEY from the environment). Override the model with CASCADE_MODEL.

export const runtime = "nodejs";
export const maxDuration = 60;

const MODEL = process.env.CASCADE_MODEL ?? "claude-sonnet-4-6";

interface CascadeRequest {
  stageId: StageId;
  concept: string;
  referenceDoc?: string;
  template?: string;
  revision?: StageRevisionInput;
  prior?: PriorStage[];
}

export async function POST(req: NextRequest) {
  if (!process.env.ANTHROPIC_API_KEY) {
    return new Response(
      "ANTHROPIC_API_KEY is not set. Add it to .env.local and restart the dev server.",
      { status: 500 },
    );
  }

  let body: CascadeRequest;
  try {
    body = (await req.json()) as CascadeRequest;
  } catch {
    return new Response("Invalid JSON body", { status: 400 });
  }

  const { stageId, concept, referenceDoc, template, revision, prior = [] } = body;

  const stage = stageId && STAGE_BY_ID[stageId];
  if (!stage) {
    return new Response(`Unknown stage: ${stageId}`, { status: 400 });
  }
  if (!concept || !concept.trim()) {
    return new Response("A product concept is required", { status: 400 });
  }

  const context = buildStageContext({
    concept,
    referenceDoc,
    template,
    revision,
    prior,
  });

  // The AI SDK routes gateway/provider errors to onError and ends the stream
  // rather than throwing, so we capture it here.
  let capturedError: unknown = null;
  const result = streamText({
    model: anthropic(MODEL),
    system: stage.system,
    prompt: context,
    temperature: 0.7,
    maxOutputTokens: 5000,
    onError: ({ error }) => {
      capturedError = error;
    },
  });

  // Peek the first chunk so pre-stream failures (bad key, no credit card on
  // file, rate limits) come back as a real error status the client can show,
  // instead of an empty 200 that silently renders a blank card.
  const encoder = new TextEncoder();
  const iterator = result.textStream[Symbol.asyncIterator]();
  const first = await iterator.next();

  if (first.done) {
    // Empty stream: either a genuine no-op or an error captured via onError.
    // Let any onError microtask settle, then surface it.
    await new Promise((r) => setTimeout(r, 0));
    if (capturedError) {
      return new Response(friendlyError(capturedError), { status: 502 });
    }
  }

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        if (!first.done) controller.enqueue(encoder.encode(first.value));
        while (true) {
          const { value, done } = await iterator.next();
          if (done) break;
          controller.enqueue(encoder.encode(value));
        }
        if (capturedError) throw capturedError;
        controller.close();
      } catch (err) {
        controller.error(err);
      }
    },
  });

  return new Response(stream, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}

/** Turns an AI SDK / gateway error into a short, user-facing message. */
function friendlyError(err: unknown): string {
  const raw =
    (typeof err === "object" && err && "message" in err
      ? String((err as { message: unknown }).message)
      : String(err)) || "Generation failed.";
  if (/credit|balance|insufficient_quota|billing/i.test(raw)) {
    return "Anthropic rejected the request for billing/credit reasons. Check your API credits, then re-run.";
  }
  if (/api[\s_-]?key|unauthorized|401|authentication|invalid x-api-key/i.test(raw)) {
    return "Anthropic rejected the API key. Check ANTHROPIC_API_KEY in .env.local.";
  }
  return raw.slice(0, 300);
}
